
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenges;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.IntStream;

import static java.util.stream.Collectors.joining;

public class Challenge3 {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        /*BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(System.getenv("OUTPUT_PATH")));

        int k = Integer.parseInt(bufferedReader.readLine().trim());

        int pCount = Integer.parseInt(bufferedReader.readLine().trim());

        List<Integer> p = IntStream.range(0, pCount).mapToObj(i -> {
            try {
                return bufferedReader.readLine().replaceAll("\\s+$", "");
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        })
                .map(String::trim)
                .map(Integer::parseInt)
                .collect(toList());

        int qCount = Integer.parseInt(bufferedReader.readLine().trim());

        List<Integer> q = IntStream.range(0, qCount).mapToObj(i -> {
            try {
                return bufferedReader.readLine().replaceAll("\\s+$", "");
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        })
                .map(String::trim)
                .map(Integer::parseInt)
                .collect(toList());
*/
        List<Integer> result = Result.kthPerson(2, Arrays.asList(1, 2, 3, 4), Arrays.asList(1, 3, 4));
        result.stream().forEach(System.out::println);

       /* bufferedWriter.write(
                result.stream()
                        .map(Object::toString)
                        .collect(joining("\n"))
                        + "\n"
        );
        bufferedReader.close();
        bufferedWriter.close();*/
    }

    static class Result {
        public static List<Integer> kthPerson(int k, List<Integer> p, List<Integer> q) {
            List<Integer> pList = new LinkedList<>(p);
            List<Integer> result = new ArrayList<>();
            AtomicReference<Integer> totalPersonLeft = new AtomicReference<>(0);
            q.stream().forEach(busArrivalTime -> {
                List<Integer> personsOnBus = new ArrayList<>();
                List<Integer> personsLeft = new ArrayList<>();
                p.stream().forEach(person -> {
                    if (person < busArrivalTime) {
                        personsLeft.add(person);
                    }
                });
                personsLeft.stream().forEach(personLeft -> pList.remove(personLeft));
                IntStream.range(0, k).forEach(passengerIndex -> {
                    if (pList.size() > passengerIndex) {
                        personsOnBus.add(pList.get(passengerIndex));
                        totalPersonLeft.set(totalPersonLeft.get() + 1);
                    }
                });
                if (personsOnBus.size() < k) {
                    result.add(0);
                } else {
                    result.add(totalPersonLeft.get());
                }
            });
            return result;
        }
    }
}
