/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class Challenge1Test {

    @Test
    public void testAppHasAGreeting() {
        Challenge1 classUnderTest = new Challenge1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
